import os
import sys
import json
import shutil
import random
from datetime import datetime

# Python Builder Version: 1.0.1 (Fallback for Node.js)

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC_RI = os.path.join(ROOT, 'ri')
DIST = os.path.join(ROOT, 'dist')
DIST_RI = os.path.join(DIST, 'ri')
CONFIG_FILE = os.path.join(ROOT, 'config.json')

def get_config():
    config = {'domain': ''}
    if 'DOMAIN' in os.environ:
        config['domain'] = os.environ['DOMAIN']
        print('Loaded domain from environment variable.')
    elif os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, 'r', encoding='utf-8') as f:
                parsed = json.load(f)
                if 'domain' in parsed:
                    config['domain'] = parsed['domain']
            print('Loaded domain from config.json.')
        except Exception as e:
            print(f'Failed to parse config.json: {e}')
    
    if config['domain']:
        config['domain'] = config['domain'].rstrip('/')
    print(f'Using domain prefix: "{config["domain"]}"')
    return config

def main():
    print('Starting Python build...')
    config = get_config()
    
    # 1. Clean/Create Dist
    if os.path.exists(DIST):
        shutil.rmtree(DIST)
    os.makedirs(DIST, exist_ok=True)
    os.makedirs(DIST_RI, exist_ok=True)
    with open(os.path.join(DIST, '.nojekyll'), 'w') as f:
        pass
        
    counts = {}
    types = ['h', 'v']
    
    for t in types:
        src_folder = os.path.join(SRC_RI, t)
        dist_folder = os.path.join(DIST_RI, t)
        
        if not os.path.exists(src_folder):
            print(f"Source folder not found: {src_folder}")
            counts[t] = 0
            continue
            
        os.makedirs(dist_folder, exist_ok=True)
        files = [f for f in os.listdir(src_folder) if f.lower().endswith(('.webp', '.jpg', '.jpeg', '.png', '.gif'))]
        random.shuffle(files)
        
        for idx, file in enumerate(files):
            src_path = os.path.join(src_folder, file)
            dest_path = os.path.join(dist_folder, f"{idx + 1}.webp")
            shutil.copy2(src_path, dest_path)
            
        counts[t] = len(files)
        print(f"Processed {t}: {counts[t]} images.")
        
    # Read the JS template from build.js (too complex to maintain two copies, we just generate script matching original logic)
    # Actually wait, we can just regenerate the exact same strings as build.js JS content

    js_content = """
/**
 * Static Random Pic API
 * Generated by build script
 */
(function() {
    var counts = """ + json.dumps(counts) + """;
    var domain = '""" + config['domain'] + """';
    
    // Support relative paths for testing on preview domains and when served from the same origin
    if (typeof window !== 'undefined') {
        if (window.location.origin === domain) {
            domain = '';
        }
    }
    
    // State management for session consistency
    var sessionRandomH = null;
    var sessionRandomV = null;

    // Helper: Get random URL for a type (h or v), persistent per session
    function getRandomUrl(type) {
        if (!counts[type] || counts[type] === 0) return '';
        if (type === 'h' && sessionRandomH) return sessionRandomH;
        if (type === 'v' && sessionRandomV) return sessionRandomV;
        var num = Math.floor(Math.random() * counts[type]) + 1;
        var url = domain + '/ri/' + type + '/' + num + '.webp';
        if (type === 'h') sessionRandomH = url;
        if (type === 'v') sessionRandomV = url;
        return url;
    }

    window.getRandomPicH = function() { return getRandomUrl('h'); };
    window.getRandomPicV = function() { return getRandomUrl('v'); };

    function setRandomBackground() { 
         const bgUrl = getRandomUrl('h');
         const bgBox = document.getElementById('bg-box'); 
         if (bgBox) { 
             const img = new Image(); 
             img.onload = function() { 
                 bgBox.style.backgroundImage = `url('${bgUrl}')`; 
                 bgBox.classList.add('loaded'); 
                 console.log('Random background loaded:', bgUrl); 
                 document.documentElement.style.setProperty('--card-bg', 'var(--card-bg-transparent)'); 
                 document.documentElement.style.setProperty('--float-panel-bg', 'var(--float-panel-bg-transparent)'); 
             }; 
             img.onerror = function() { console.error('Failed to load background image:', bgUrl); }; 
             img.src = bgUrl; 
         } else { 
             initGenericBackgrounds();
         } 
    }

    function initImgTags() {
        var imgTags = document.getElementsByTagName('img');
        for (var i = 0; i < imgTags.length; i++) {
            var img = imgTags[i];
            var alt = img.getAttribute('alt');
            var src = img.getAttribute('src');
            if (alt === 'random:h' || (src && src.indexOf('/random/h') !== -1)) img.src = getRandomUrl('h');
            else if (alt === 'random:v' || (src && src.indexOf('/random/v') !== -1)) img.src = getRandomUrl('v');
        }
    }

    function initGenericBackgrounds() {
        var bgElements = document.querySelectorAll('[data-random-bg]');
        bgElements.forEach(function(el) {
            if (el.id === 'bg-box') return;
            var type = el.getAttribute('data-random-bg');
            if (type === 'h' || type === 'v') {
                var url = getRandomUrl(type);
                if (url) {
                    var img = new Image();
                    img.onload = function() {
                        el.style.backgroundImage = 'url("' + url + '")';
                        el.classList.add('loaded');
                    };
                    img.src = url;
                }
            }
        });
    }

    function init() {
        setRandomBackground();
        initImgTags();
    }
  
    if (document.readyState === 'loading') { 
        document.addEventListener('DOMContentLoaded', init); 
    } else { 
        init(); 
    } 
  
    function setupSwup() {
        if (window.swup && window.swup.hooks) {
            window.swup.hooks.on('content:replace', init);
        }
    }

    if (window.swup) setupSwup();
    else document.addEventListener('swup:enable', setupSwup);
    document.addEventListener('swup:contentReplaced', init); 
})();
"""
    with open(os.path.join(DIST, 'random.js'), 'w', encoding='utf-8') as f:
        f.write(js_content.strip())
        
    index_src = os.path.join(ROOT, 'index.html')
    if os.path.exists(index_src) and os.path.getsize(index_src) > 0:
        shutil.copy2(index_src, os.path.join(DIST, 'index.html'))
        print('Copied index.html to dist')
    else:
        create_demo_html()

    api_data = {
        'lastBuild': datetime.utcnow().isoformat() + 'Z',
        'domain': config['domain'],
        'counts': counts,
        'images': {
            'h': [f"{config['domain']}/ri/h/{i+1}.webp" for i in range(counts['h'])],
            'v': [f"{config['domain']}/ri/v/{i+1}.webp" for i in range(counts['v'])]
        }
    }
    with open(os.path.join(DIST, 'api.json'), 'w', encoding='utf-8') as f:
        json.dump(api_data, f, indent=2)
    print('Generated api.json')
    
    create_gallery_html(counts, config)
    print('Build complete. Output is in /dist folder.')

def create_gallery_html(counts, config):
    lib_dir = os.path.join(DIST, 'lib')
    os.makedirs(lib_dir, exist_ok=True)
    
    # Try to copy assets
    masonry_src = os.path.join(ROOT, 'node_modules', 'masonry-layout', 'dist', 'masonry.pkgd.min.js')
    imagesloaded_src = os.path.join(ROOT, 'node_modules', 'imagesloaded', 'imagesloaded.pkgd.min.js')
    lozad_src = os.path.join(ROOT, 'node_modules', 'lozad', 'dist', 'lozad.min.js')
    ether_src = os.path.join(ROOT, 'assets', 'LiquidEther.jsx')
    
    try:
        if os.path.exists(masonry_src): shutil.copy2(masonry_src, os.path.join(lib_dir, 'masonry.pkgd.min.js'))
        if os.path.exists(imagesloaded_src): shutil.copy2(imagesloaded_src, os.path.join(lib_dir, 'imagesloaded.pkgd.min.js'))
        if os.path.exists(lozad_src): shutil.copy2(lozad_src, os.path.join(lib_dir, 'lozad.min.js'))
        if os.path.exists(ether_src): shutil.copy2(ether_src, os.path.join(lib_dir, 'LiquidEther.jsx'))
    except Exception as e:
        print(f"Warning: Could not copy all libraries: {e}")

    gallery_content = ''
    nav_buttons = '<button class="filter-btn active" onclick="filterGallery(\'all\')">All</button>'
    
    types = list(counts.keys())
    for t in types:
        count = counts[t]
        if count == 0: continue
        
        max_preview = 100
        nav_buttons += f'<button class="filter-btn" onclick="filterGallery(\'{t}\')">{t.upper()} ({count})</button>'
        
        items_html = ''
        step = count // max_preview if count > max_preview else 1
        i = 1
        drawn = 0
        while i <= count and drawn < max_preview:
            url = f"/ri/{t}/{i}.webp"
            aspect = "16/9" if t == 'h' else "9/16"
            items_html += f'\n            <div class="grid-item" style="aspect-ratio: {aspect};"><img class="lozad" data-src="{url}" alt="{t}-{i}"></div>'
            i += step
            drawn += 1
            
        gallery_content += f'''
        <section id="section-{t}" class="gallery-section">
            <h2>Folder: {t} (Showing sample of {drawn} images)</h2>
            <div class="grid" id="grid-{t}">
                <div class="grid-sizer"></div>{items_html}
            </div>
        </section>
        '''

    html_content = f'''<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gallery - Static Random Pic API</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #000;
            color: #fff;
            min-height: 100vh;
        }}
        #bg-root {{
            position: fixed;
            top: 0; left: 0; width: 100vw; height: 100vh;
            z-index: -1;
        }}
        h1 {{ text-align: center; color: rgba(255, 255, 255, 0.9); margin-bottom: 20px; text-shadow: 0 2px 10px rgba(0,0,0,0.5); font-weight: 800; letter-spacing: 1px; }}
        
        /* Filter Nav */
        .filter-nav {{ text-align: center; margin-bottom: 30px; }}
        .filter-btn {{
            background: rgba(255, 255, 255, 0.1); border: 1px solid rgba(255, 255, 255, 0.2); padding: 8px 16px; margin: 0 5px;
            border-radius: 20px; cursor: pointer; transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1); font-size: 14px;
            color: rgba(255, 255, 255, 0.8);
            backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px);
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }}
        .filter-btn:hover {{ background: rgba(255, 255, 255, 0.2); border-color: rgba(255, 255, 255, 0.4); transform: translateY(-1px); color: #fff; }}
        .filter-btn.active {{ background: rgba(255, 255, 255, 0.9); color: #000; border-color: #fff; box-shadow: 0 0 15px rgba(255,255,255,0.4); }}

        h2 {{ border-bottom: 1px solid rgba(255,255,255,0.2); padding-bottom: 10px; margin-top: 40px; color: rgba(255, 255, 255, 0.9); text-transform: uppercase; font-size: 1.2rem; text-shadow: 0 2px 5px rgba(0,0,0,0.5); }}
        
        /* Masonry Grid */
        .grid {{ margin: 0 auto; }}
        .grid-sizer, .grid-item {{ width: 23%; margin-bottom: 15px; }}
        .grid-item {{
            float: left;
            background: rgba(255, 255, 255, 0.05);
            border-radius: 12px;
            overflow: hidden;
            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
            backdrop-filter: blur(8px); -webkit-backdrop-filter: blur(8px);
            border: 1px solid rgba(255, 255, 255, 0.1);
            transition: all 0.3s ease;
        }}
        .grid-item:hover {{
            transform: translateY(-5px);
            box-shadow: 0 12px 40px rgba(0, 0, 0, 0.5);
            border-color: rgba(255, 255, 255, 0.3);
        }}
        .grid-item.content-loaded {{ min-height: 0; background-color: rgba(255, 255, 255, 0.1); }}
        .grid-item img {{ display: block; width: 100%; height: auto; opacity: 0; transition: opacity 0.4s; }}
        .grid-item img[data-loaded="true"] {{ opacity: 1; }}

        /* Responsive */
        @media (max-width: 1200px) {{ .grid-sizer, .grid-item {{ width: 31%; }} }}
        @media (max-width: 800px) {{ .grid-sizer, .grid-item {{ width: 48%; }} }}
        @media (max-width: 500px) {{ .grid-sizer, .grid-item {{ width: 100%; }} }}
    </style>
</head>
<body>
    <div id="bg-root"></div>
    <div style="position: relative; z-index: 1;">
        <h1>Static Image Gallery</h1>
        <div class="filter-nav">
            {nav_buttons}
        </div>
        {gallery_content}
    </div>

    <script src="https://unpkg.com/react@18/umd/react.production.min.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js" crossorigin></script>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
    <script src="https://unpkg.com/three@0.160.0/build/three.min.js"></script>
    
    <script type="text/babel" src="lib/LiquidEther.jsx"></script>

    <script type="text/babel">
        const LiquidBgWrapper = () => {{
            const [loaded, setLoaded] = React.useState(false);
            React.useEffect(() => {{
                const check = () => {{
                    if (window.LiquidEther) setLoaded(true);
                    else setTimeout(check, 50);
                }};
                check();
            }}, []);
            if (!loaded) return null;
            const LiquidEther = window.LiquidEther;
            return <LiquidEther />;
        }};
        const rootNode = document.getElementById('bg-root');
        const root = ReactDOM.createRoot(rootNode);
        root.render(<LiquidBgWrapper />);
    </script>
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
    <script src="https://unpkg.com/imagesloaded@5/imagesloaded.pkgd.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/lozad/dist/lozad.min.js"></script>
    <script>
        var masonryInstances = [];
        document.addEventListener('DOMContentLoaded', function() {{
            var grids = document.querySelectorAll('.grid');
            grids.forEach(function(grid) {{
                var msnry = new Masonry(grid, {{
                    itemSelector: '.grid-item', columnWidth: '.grid-sizer', percentPosition: true, gutter: 15
                }});
                masonryInstances.push(msnry);
            }});
            let layoutTimer = null;
            const observer = lozad('.lozad', {{
                rootMargin: '500px 0px',
                loaded: function(el) {{
                    const onImgLoad = function() {{
                        el.setAttribute('data-loaded', true);
                        el.closest('.grid-item').classList.add('content-loaded');
                        if (!layoutTimer) {{
                            layoutTimer = setTimeout(() => {{ masonryInstances.forEach(msnry => msnry.layout()); layoutTimer = null; }}, 300);
                        }}
                    }};
                    if (el.complete) onImgLoad(); else el.onload = onImgLoad;
                }}
            }});
            observer.observe();
            setTimeout(() => {{ masonryInstances.forEach(msnry => msnry.layout()); }}, 100);
        }});
        function filterGallery(type) {{
            document.querySelectorAll('.filter-btn').forEach(btn => btn.classList.remove('active'));
            event.target.classList.add('active');
            document.querySelectorAll('.gallery-section').forEach(sec => {{
                if (type === 'all' || sec.id === 'section-' + type) sec.style.display = 'block';
                else sec.style.display = 'none';
            }});
            setTimeout(() => {{ masonryInstances.forEach(msnry => msnry.layout()); }}, 10);
        }}
    </script>
</body>
</html>'''
    
    with open(os.path.join(DIST, 'gallery.html'), 'w', encoding='utf-8') as f:
        f.write(html_content)
    print('Created gallery.html in dist')

def create_demo_html():
    html_content = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Static Random Pic API Demo</title>
    <style>
        body { font-family: sans-serif; max-width: 800px; margin: 20px auto; padding: 20px; }
        .card { border: 1px solid #ccc; padding: 20px; margin-bottom: 20px; border-radius: 8px; }
        img { max-width: 100%; height: auto; border-radius: 4px; display: block; background: #eee; min-height: 200px; }
        .btn { display: inline-block; padding: 10px 20px; background: #007bff; color: white; text-decoration: none; border-radius: 4px; }
        .bg-box { width: 100%; height: 200px; background-size: cover; background-position: center; border-radius: 4px; border: 1px dashed #999; display: flex; align-items: center; justify-content: center; color: white; text-shadow: 0 1px 3px rgba(0,0,0,0.8); font-weight: bold; }
    </style>
</head>
<body>
    <h1>Static Random Pic API (Client-Side)</h1>
    <p>
        This is a static implementation. Images are randomized at build time.
        <a href="gallery.html" class="btn" style="float: right;">View Gallery</a>
    </p>

    <div class="card">
        <h2>Horizontal Image (横屏)</h2>
        <p>Using <code>&lt;img alt="random:h"&gt;</code>:</p>
        <img alt="random:h" title="Random Horizontal Image" />
        <br>
        <p>Background Image (<code>data-random-bg="h"</code>):</p>
        <div class="bg-box" data-random-bg="h">Background Image</div>
    </div>

    <div class="card">
        <h2>Vertical Image (竖屏)</h2>
        <p>Using <code>&lt;img alt="random:v"&gt;</code>:</p>
        <img alt="random:v" style="max-height: 400px;" title="Random Vertical Image" />
    </div>
    <script src="random.js"></script>
</body>
</html>"""
    with open(os.path.join(DIST, 'index.html'), 'w', encoding='utf-8') as f:
        f.write(html_content)
    print('Created demo index.html in dist')

if __name__ == "__main__":
    main()
