import os
import sys
import json
import shutil
import random
from datetime import datetime

# Python Builder Version: 1.0.1 (Fallback for Node.js)

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC_RI = os.path.join(ROOT, 'ri')
DIST = os.path.join(ROOT, 'dist')
DIST_RI = os.path.join(DIST, 'ri')
CONFIG_FILE = os.path.join(ROOT, 'config.json')

def get_config():
    config = {'domain': ''}
    if 'DOMAIN' in os.environ:
        config['domain'] = os.environ['DOMAIN']
        print('Loaded domain from environment variable.')
    elif os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, 'r', encoding='utf-8') as f:
                parsed = json.load(f)
                if 'domain' in parsed:
                    config['domain'] = parsed['domain']
            print('Loaded domain from config.json.')
        except Exception as e:
            print(f'Failed to parse config.json: {e}')
    
    if config['domain']:
        config['domain'] = config['domain'].rstrip('/')
    print(f'Using domain prefix: "{config["domain"]}"')
    return config

def main():
    print('Starting Python build...')
    config = get_config()
    
    # 1. Clean/Create Dist
    if os.path.exists(DIST):
        shutil.rmtree(DIST)
    os.makedirs(DIST, exist_ok=True)
    os.makedirs(DIST_RI, exist_ok=True)
    with open(os.path.join(DIST, '.nojekyll'), 'w') as f:
        pass
        
    counts = {}
    types = ['h', 'v']
    
    for t in types:
        src_folder = os.path.join(SRC_RI, t)
        dist_folder = os.path.join(DIST_RI, t)
        
        if not os.path.exists(src_folder):
            print(f"Source folder not found: {src_folder}")
            counts[t] = 0
            continue
            
        os.makedirs(dist_folder, exist_ok=True)
        files = [f for f in os.listdir(src_folder) if f.lower().endswith(('.webp', '.jpg', '.jpeg', '.png', '.gif'))]
        random.shuffle(files)
        
        for idx, file in enumerate(files):
            src_path = os.path.join(src_folder, file)
            dest_path = os.path.join(dist_folder, f"{idx + 1}.webp")
            shutil.copy2(src_path, dest_path)
            
        counts[t] = len(files)
        print(f"Processed {t}: {counts[t]} images.")
        
    # Read the JS template from build.js (too complex to maintain two copies, we just generate script matching original logic)
    # Actually wait, we can just regenerate the exact same strings as build.js JS content

    js_content = """
/**
 * Static Random Pic API
 * Generated by build script
 */
(function() {
    var counts = """ + json.dumps(counts) + """;
    var domain = '""" + config['domain'] + """';
    
    // Support relative paths for testing on preview domains and when served from the same origin
    if (typeof window !== 'undefined') {
        if (window.location.origin === domain) {
            domain = '';
        }
    }
    
    // State management for session consistency
    var sessionRandomH = null;
    var sessionRandomV = null;

    // Helper: Get random URL for a type (h or v), persistent per session
    function getRandomUrl(type) {
        if (!counts[type] || counts[type] === 0) return '';
        if (type === 'h' && sessionRandomH) return sessionRandomH;
        if (type === 'v' && sessionRandomV) return sessionRandomV;
        var num = Math.floor(Math.random() * counts[type]) + 1;
        var url = domain + '/ri/' + type + '/' + num + '.webp';
        if (type === 'h') sessionRandomH = url;
        if (type === 'v') sessionRandomV = url;
        return url;
    }

    window.getRandomPicH = function() { return getRandomUrl('h'); };
    window.getRandomPicV = function() { return getRandomUrl('v'); };

    function setRandomBackground() { 
         const bgUrl = getRandomUrl('h');
         const bgBox = document.getElementById('bg-box'); 
         if (bgBox) { 
             const img = new Image(); 
             img.onload = function() { 
                 bgBox.style.backgroundImage = `url('${bgUrl}')`; 
                 bgBox.classList.add('loaded'); 
                 console.log('Random background loaded:', bgUrl); 
                 document.documentElement.style.setProperty('--card-bg', 'var(--card-bg-transparent)'); 
                 document.documentElement.style.setProperty('--float-panel-bg', 'var(--float-panel-bg-transparent)'); 
             }; 
             img.onerror = function() { console.error('Failed to load background image:', bgUrl); }; 
             img.src = bgUrl; 
         } else { 
             initGenericBackgrounds();
         } 
    }

    function initImgTags() {
        var imgTags = document.getElementsByTagName('img');
        for (var i = 0; i < imgTags.length; i++) {
            var img = imgTags[i];
            var alt = img.getAttribute('alt');
            var src = img.getAttribute('src');
            if (alt === 'random:h' || (src && src.indexOf('/random/h') !== -1)) img.src = getRandomUrl('h');
            else if (alt === 'random:v' || (src && src.indexOf('/random/v') !== -1)) img.src = getRandomUrl('v');
        }
    }

    function initGenericBackgrounds() {
        var bgElements = document.querySelectorAll('[data-random-bg]');
        bgElements.forEach(function(el) {
            if (el.id === 'bg-box') return;
            var type = el.getAttribute('data-random-bg');
            if (type === 'h' || type === 'v') {
                var url = getRandomUrl(type);
                if (url) {
                    var img = new Image();
                    img.onload = function() {
                        el.style.backgroundImage = 'url("' + url + '")';
                        el.classList.add('loaded');
                    };
                    img.src = url;
                }
            }
        });
    }

    function init() {
        setRandomBackground();
        initImgTags();
    }
  
    if (document.readyState === 'loading') { 
        document.addEventListener('DOMContentLoaded', init); 
    } else { 
        init(); 
    } 
  
    function setupSwup() {
        if (window.swup && window.swup.hooks) {
            window.swup.hooks.on('content:replace', init);
        }
    }

    if (window.swup) setupSwup();
    else document.addEventListener('swup:enable', setupSwup);
    document.addEventListener('swup:contentReplaced', init); 
})();
"""
    with open(os.path.join(DIST, 'random.js'), 'w', encoding='utf-8') as f:
        f.write(js_content.strip())
        
    create_premium_html(counts)

    api_data = {
        'lastBuild': datetime.utcnow().isoformat() + 'Z',
        'domain': config['domain'],
        'counts': counts,
        'images': {
            'h': [f"{config['domain']}/ri/h/{i+1}.webp" for i in range(counts['h'])],
            'v': [f"{config['domain']}/ri/v/{i+1}.webp" for i in range(counts['v'])]
        }
    }
    with open(os.path.join(DIST, 'api.json'), 'w', encoding='utf-8') as f:
        json.dump(api_data, f, indent=2)
    print('Generated api.json')
    
    create_gallery_html(counts, config)
    print('Build complete. Output is in /dist folder.')

def create_gallery_html(counts, config):
    lib_dir = os.path.join(DIST, 'lib')
    os.makedirs(lib_dir, exist_ok=True)
    
    # Try to copy assets
    masonry_src = os.path.join(ROOT, 'node_modules', 'masonry-layout', 'dist', 'masonry.pkgd.min.js')
    imagesloaded_src = os.path.join(ROOT, 'node_modules', 'imagesloaded', 'imagesloaded.pkgd.min.js')
    lozad_src = os.path.join(ROOT, 'node_modules', 'lozad', 'dist', 'lozad.min.js')
    ether_src = os.path.join(ROOT, 'assets', 'LiquidEther.jsx')
    
    try:
        if os.path.exists(masonry_src): shutil.copy2(masonry_src, os.path.join(lib_dir, 'masonry.pkgd.min.js'))
        if os.path.exists(imagesloaded_src): shutil.copy2(imagesloaded_src, os.path.join(lib_dir, 'imagesloaded.pkgd.min.js'))
        if os.path.exists(lozad_src): shutil.copy2(lozad_src, os.path.join(lib_dir, 'lozad.min.js'))
        if os.path.exists(ether_src): shutil.copy2(ether_src, os.path.join(lib_dir, 'LiquidEther.jsx'))
    except Exception as e:
        print(f"Warning: Could not copy all libraries: {e}")

    gallery_content = ''
    nav_buttons = '<button class="filter-btn active" onclick="filterGallery(\'all\')">All</button>'
    
    types = list(counts.keys())
    for t in types:
        count = counts[t]
        if count == 0: continue
        
        max_preview = 100
        nav_buttons += f'<button class="filter-btn" onclick="filterGallery(\'{t}\')">{t.upper()} ({count})</button>'
        
        items_html = ''
        step = count // max_preview if count > max_preview else 1
        i = 1
        drawn = 0
        while i <= count and drawn < max_preview:
            url = f"/ri/{t}/{i}.webp"
            aspect = "16/9" if t == 'h' else "9/16"
            items_html += f'\n            <div class="grid-item" style="aspect-ratio: {aspect};"><img class="lozad" data-src="{url}" alt="{t}-{i}"></div>'
            i += step
            drawn += 1
            
        gallery_content += f'''
        <section id="section-{t}" class="gallery-section">
            <h2>Folder: {t} (Showing sample of {drawn} images)</h2>
            <div class="grid" id="grid-{t}">
                <div class="grid-sizer"></div>{items_html}
            </div>
        </section>
        '''

    html_content = f'''<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gallery - Static Random Pic API</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #000;
            color: #fff;
            min-height: 100vh;
        }}
        #bg-root {{
            position: fixed;
            top: 0; left: 0; width: 100vw; height: 100vh;
            z-index: -1;
        }}
        h1 {{ text-align: center; color: rgba(255, 255, 255, 0.9); margin-bottom: 20px; text-shadow: 0 2px 10px rgba(0,0,0,0.5); font-weight: 800; letter-spacing: 1px; }}
        
        /* Filter Nav */
        .filter-nav {{ text-align: center; margin-bottom: 30px; }}
        .filter-btn {{
            background: rgba(255, 255, 255, 0.1); border: 1px solid rgba(255, 255, 255, 0.2); padding: 8px 16px; margin: 0 5px;
            border-radius: 20px; cursor: pointer; transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1); font-size: 14px;
            color: rgba(255, 255, 255, 0.8);
            backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px);
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }}
        .filter-btn:hover {{ background: rgba(255, 255, 255, 0.2); border-color: rgba(255, 255, 255, 0.4); transform: translateY(-1px); color: #fff; }}
        .filter-btn.active {{ background: rgba(255, 255, 255, 0.9); color: #000; border-color: #fff; box-shadow: 0 0 15px rgba(255,255,255,0.4); }}

        h2 {{ border-bottom: 1px solid rgba(255,255,255,0.2); padding-bottom: 10px; margin-top: 40px; color: rgba(255, 255, 255, 0.9); text-transform: uppercase; font-size: 1.2rem; text-shadow: 0 2px 5px rgba(0,0,0,0.5); }}
        
        /* Masonry Grid */
        .grid {{ margin: 0 auto; }}
        .grid-sizer, .grid-item {{ width: 23%; margin-bottom: 15px; }}
        .grid-item {{
            float: left;
            background: rgba(255, 255, 255, 0.05);
            border-radius: 12px;
            overflow: hidden;
            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
            backdrop-filter: blur(8px); -webkit-backdrop-filter: blur(8px);
            border: 1px solid rgba(255, 255, 255, 0.1);
            transition: all 0.3s ease;
        }}
        .grid-item:hover {{
            transform: translateY(-5px);
            box-shadow: 0 12px 40px rgba(0, 0, 0, 0.5);
            border-color: rgba(255, 255, 255, 0.3);
        }}
        .grid-item.content-loaded {{ min-height: 0; background-color: rgba(255, 255, 255, 0.1); }}
        .grid-item img {{ display: block; width: 100%; height: auto; opacity: 0; transition: opacity 0.4s; }}
        .grid-item img[data-loaded="true"] {{ opacity: 1; }}

        /* Responsive */
        @media (max-width: 1200px) {{ .grid-sizer, .grid-item {{ width: 31%; }} }}
        @media (max-width: 800px) {{ .grid-sizer, .grid-item {{ width: 48%; }} }}
        @media (max-width: 500px) {{ .grid-sizer, .grid-item {{ width: 100%; }} }}
    </style>
</head>
<body>
    <div id="bg-root"></div>
    <div style="position: relative; z-index: 1;">
        <h1>Static Image Gallery</h1>
        <div class="filter-nav">
            {nav_buttons}
        </div>
        {gallery_content}
    </div>

    <script src="https://unpkg.com/react@18/umd/react.production.min.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js" crossorigin></script>
    <script src="https://unpkg.com/@babel/standalone@7.23.10/babel.min.js"></script>
    <script src="https://unpkg.com/three@0.160.0/build/three.min.js"></script>
    
    <script type="text/babel" src="lib/LiquidEther.jsx"></script>

    <script type="text/babel">
        const LiquidBgWrapper = () => {{
            const [loaded, setLoaded] = React.useState(false);
            React.useEffect(() => {{
                const check = () => {{
                    if (window.LiquidEther) setLoaded(true);
                    else setTimeout(check, 50);
                }};
                check();
            }}, []);
            if (!loaded) return null;
            const LiquidEther = window.LiquidEther;
            return <LiquidEther />;
        }};
        const rootNode = document.getElementById('bg-root');
        const root = ReactDOM.createRoot(rootNode);
        root.render(<LiquidBgWrapper />);
    </script>
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
    <script src="https://unpkg.com/imagesloaded@5/imagesloaded.pkgd.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/lozad/dist/lozad.min.js"></script>
    <script>
        var masonryInstances = [];
        document.addEventListener('DOMContentLoaded', function() {{
            var grids = document.querySelectorAll('.grid');
            grids.forEach(function(grid) {{
                var msnry = new Masonry(grid, {{
                    itemSelector: '.grid-item', columnWidth: '.grid-sizer', percentPosition: true, gutter: 15
                }});
                masonryInstances.push(msnry);
            }});
            let layoutTimer = null;
            const observer = lozad('.lozad', {{
                rootMargin: '500px 0px',
                loaded: function(el) {{
                    const onImgLoad = function() {{
                        el.setAttribute('data-loaded', true);
                        el.closest('.grid-item').classList.add('content-loaded');
                        if (!layoutTimer) {{
                            layoutTimer = setTimeout(() => {{ masonryInstances.forEach(msnry => msnry.layout()); layoutTimer = null; }}, 300);
                        }}
                    }};
                    if (el.complete) onImgLoad(); else el.onload = onImgLoad;
                }}
            }});
            observer.observe();
            setTimeout(() => {{ masonryInstances.forEach(msnry => msnry.layout()); }}, 100);
        }});
        function filterGallery(type) {{
            document.querySelectorAll('.filter-btn').forEach(btn => btn.classList.remove('active'));
            event.target.classList.add('active');
            document.querySelectorAll('.gallery-section').forEach(sec => {{
                if (type === 'all' || sec.id === 'section-' + type) sec.style.display = 'block';
                else sec.style.display = 'none';
            }});
            setTimeout(() => {{ masonryInstances.forEach(msnry => msnry.layout()); }}, 10);
        }}
    </script>
</body>
</html>'''
    
    with open(os.path.join(DIST, 'gallery.html'), 'w', encoding='utf-8') as f:
        f.write(html_content)
    print('Created gallery.html in dist')

def create_premium_html(counts):
    home_app_path = os.path.join(ROOT, 'assets', 'home-app.jsx')
    liquid_ether_path = os.path.join(ROOT, 'assets', 'liquid-ether-engine.js')
    
    with open(home_app_path, 'r', encoding='utf-8') as f:
        home_code = f.read()
    with open(liquid_ether_path, 'r', encoding='utf-8') as f:
        ether_code = f.read()

    html = """<!DOCTYPE html>
<html lang="zh-TW">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Static Random Pic API - Premium Delivery</title>
<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🖼️</text></svg>">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800&family=Outfit:wght@400;700;900&display=swap" rel="stylesheet">
<style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{--a:#a78bfa;--ap:#f472b6;--ag:rgba(167,139,250,.35);--gl:rgba(255,255,255,.06);--gb:rgba(255,255,255,.1);--bg:#07070f;--text:#e2e8f0;--card-bg:rgba(255,255,255,.02);--card-border:rgba(255,255,255,.06);--card-hover:rgba(255,255,255,.15);--btn-bg:rgba(255,255,255,.9);--btn-text:#0f0f1a;--btn-sec-bg:var(--gl);--btn-sec-text:#fff;--nav-btn-bg:rgba(255,255,255,.06);--f:'Inter',system-ui,sans-serif;--fd:'Outfit',sans-serif;--e:cubic-bezier(.4,0,.2,1)}
:root[data-theme='light']{--a:#8b5cf6;--ap:#ec4899;--ag:rgba(139,92,246,.25);--gl:rgba(0,0,0,.04);--gb:rgba(0,0,0,.1);--bg:#f8fafc;--text:#0f172a;--card-bg:rgba(255,255,255,.6);--card-border:rgba(0,0,0,.08);--card-hover:rgba(0,0,0,.15);--btn-bg:#0f172a;--btn-text:#fff;--btn-sec-bg:var(--gl);--btn-sec-text:#0f172a;--nav-btn-bg:rgba(0,0,0,.05)}
html{scroll-behavior:smooth;overflow-y:scroll;min-height:100.1vh}
body{font-family:var(--f);background:var(--bg);color:var(--text);min-height:100vh;overflow-x:hidden;transition:background .4s var(--e),color .4s var(--e)}
body.hide-cursor,body.hide-cursor *{cursor:none!important}
#ether-bg{position:fixed;top:0;left:0;width:100vw;height:100vh;z-index:0;pointer-events:none}
.cur-dot{position:fixed;top:-6px;left:-6px;width:12px;height:12px;border-radius:50%;background:var(--a);pointer-events:none;z-index:99999;mix-blend-mode:difference;transition:width .2s,height .2s,top .2s,left .2s,background .2s}
.cur-dot.h{width:44px;height:44px;top:-22px;left:-22px;background:rgba(167,139,250,.12);border:1.5px solid var(--a)}
.cur-ring{position:fixed;top:-22px;left:-22px;width:44px;height:44px;border-radius:50%;border:1px solid rgba(167,139,250,.25);pointer-events:none;z-index:99998;transition:width .3s,height .3s,top .3s,left .3s,border-color .3s,opacity .3s}
.cur-ring.h{width:64px;height:64px;top:-32px;left:-32px;border-color:rgba(244,114,182,.35);opacity:.4}
@media(hover:none){.cur-dot,.cur-ring{display:none!important}body.hide-cursor,body.hide-cursor *{cursor:auto!important}}
.app{position:relative;z-index:1;max-width:1400px;margin:0 auto;padding:40px 24px 120px;min-height:100vh;overflow-anchor:none}
.flex-col{display:flex;flex-direction:column;align-items:center}
.hero{text-align:center;padding:8vh 0 10vh}
.nav-group-right{position:fixed;top:32px;right:32px;z-index:10001;display:flex;gap:12px}
.nav-btn{width:48px;height:48px;border-radius:50%;background:var(--nav-btn-bg);border:1px solid var(--gb);color:var(--text);cursor:pointer;display:flex;align-items:center;justify-content:center;transition:all 0.3s var(--e);backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);text-decoration:none;box-shadow:0 8px 32px rgba(0,0,0,0.15)}
.nav-btn:hover{transform:translateY(-2px) scale(1.1);box-shadow:0 12px 48px var(--ag);border-color:var(--a)}
.nav-btn-lang{width:54px}
.hero-title{font-family:var(--fd);font-size:clamp(2.5rem,8vw,5rem);font-weight:800;letter-spacing:-1px;margin-bottom:24px;background:linear-gradient(135deg,var(--text) 0%,var(--a) 50%,var(--ap) 100%);-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent;line-height:1.2;padding:20px 0}
.hero-title span{display:inline-block;background:inherit;-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent;animation:float 4s ease-in-out infinite;vertical-align:middle}
@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-8px)}}
.hero-sub{font-size:clamp(1rem,3vw,1.3rem);color:var(--text);opacity:.6;font-weight:300;letter-spacing:1px;margin-bottom:48px;max-width:600px;margin-left:auto;margin-right:auto}
.hero-btns{display:flex;gap:16px;justify-content:center;flex-wrap:wrap;max-width:900px;margin:0 auto}
.btn-primary,.btn-secondary{font-family:var(--f);padding:14px 28px;border-radius:999px;font-size:0.95rem;font-weight:600;cursor:pointer;backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);transition:all .3s var(--e);text-decoration:none;display:flex;align-items:center;gap:10px;white-space:nowrap}
.btn-primary{background:var(--btn-bg);color:var(--btn-text);border:1px solid transparent;box-shadow:0 0 25px var(--ag)}
.btn-primary:hover{transform:translateY(-3px);box-shadow:0 10px 40px var(--ag);border-color:var(--gb)}
.btn-secondary{background:var(--btn-sec-bg);color:var(--btn-sec-text);border:1px solid var(--gb)}
.nav-group-right{position:fixed;top:32px;right:32px;z-index:10001;display:flex;gap:12px}
.nav-group-left{position:fixed;top:32px;left:32px;z-index:10001;display:flex;gap:12px}
.nav-btn-right{position:fixed;top:32px;right:32px;z-index:10001}
.nav-btn-left{position:fixed;top:32px;left:32px;z-index:10001}
.nav-btn-lang{width:54px}
.live-demo{margin-top:20px;width:100%;max-width:1400px;margin-left:auto;margin-right:auto}
.section-title{font-family:var(--fd);font-size:2.8rem;font-weight:900;text-align:center;margin-bottom:48px;letter-spacing:-0.02em}
.demo-stack{display:flex;flex-direction:column;gap:64px;width:100%}
.v-card-wrap{width:100%;display:flex;justify-content:center}
.v-card-wrap .demo-card{width:100%;max-width:720px}
.demo-card{background:var(--card-bg);border:1px solid var(--card-border);border-radius:32px;padding:48px;transition:transform .15s ease-out,box-shadow .4s var(--e),background .4s var(--e),border-color .4s var(--e);transform-style:preserve-3d;will-change:transform;backdrop-filter:blur(24px);-webkit-backdrop-filter:blur(24px);contain:layout}
.demo-card:hover{box-shadow:0 30px 80px rgba(0,0,0,.2),0 0 40px var(--ag);border-color:var(--card-hover);background:var(--card-hover);z-index:2}
.demo-header{margin-bottom:20px}
.demo-header h3{font-family:var(--fd);font-size:1.8rem;color:var(--text);font-weight:700;margin-bottom:8px}
.code-hint{font-family:monospace;font-size:.85rem;color:var(--text);opacity:.7;background:var(--gl);padding:6px 14px;border-radius:6px;display:inline-block;border:1px solid var(--gb)}
.demo-img-box{position:relative;width:100%;border-radius:12px;overflow:hidden;background:rgba(0,0,0,.05);cursor:pointer;contain:size layout;display:block}
.demo-img-box img{width:100%;height:100%;object-fit:cover;opacity:0;transition:opacity .6s var(--e);display:block;backface-visibility:hidden}
.demo-img-box img.ok{opacity:1}
.demo-img-box .shim{position:absolute;inset:0;z-index:1;background:linear-gradient(110deg,rgba(255,255,255,.02) 30%,rgba(255,255,255,.06) 50%,rgba(255,255,255,.02) 70%);background-size:200% 100%;animation:shm 1.5s ease-in-out infinite;pointer-events:none}
.refresh-hint{position:absolute;bottom:20px;left:50%;transform:translateX(-50%) translateY(20px);background:rgba(0,0,0,.7);backdrop-filter:blur(12px);color:#fff;font-size:.75rem;padding:8px 20px;border-radius:99px;opacity:0;transition:all .3s var(--e);border:1px solid rgba(255,255,255,.1);pointer-events:none;z-index:2}
.demo-card:hover .refresh-hint{opacity:1;transform:translateX(-50%) translateY(0)}
.shine{position:absolute;inset:0;background:radial-gradient(circle at var(--sx,50%) var(--sy,50%),rgba(255,255,255,.12),transparent 50%);opacity:0;transition:opacity .3s;pointer-events:none;z-index:3}
.demo-card:hover .shine{opacity:1}
.shim{position:absolute;inset:0;background:linear-gradient(110deg,rgba(255,255,255,.02) 30%,rgba(255,255,255,.06) 50%,rgba(255,255,255,.02) 70%);background-size:200% 100%;animation:shm 1.5s ease-in-out infinite}
@keyframes shm{0%{background-position:200% 0}100%{background-position:-200% 0}}
</style>
</head>
<body>
<div id="ether-bg"></div>
<div id="root"></div>

<script src="https://unpkg.com/three@0.149.0/build/three.min.js"></script>
<script>
{ETHER_CODE}
</script>
<script>
document.addEventListener('DOMContentLoaded',function(){var b=document.getElementById('ether-bg');if(b&&typeof LiquidEtherEngine!=='undefined'){try{new LiquidEtherEngine(b,{colors:['#FF2A54','#a78bfa','#38BDF8'],autoIntensity:1.5,resolution:0.3,iterations_poisson:16,BFECC:false})}catch(e){console.warn('LiquidEther:',e)}}});
</script>
<script>window.__COUNTS__={COUNTS_JSON};</script>
<script src="https://unpkg.com/react@18/umd/react.production.min.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js" crossorigin></script>
<script src="https://unpkg.com/@babel/standalone@7.23.10/babel.min.js"></script>
<script type="text/babel">
{HOME_CODE}
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<HomeApp />);
</script>
</body>
</html>"""

    html = html.replace('{ETHER_CODE}', ether_code)
    html = html.replace('{COUNTS_JSON}', json.dumps(counts))
    html = html.replace('{HOME_CODE}', home_code)
    
    with open(os.path.join(DIST, 'index.html'), 'w', encoding='utf-8') as f:
        f.write(html)
    print('Created premium index.html (React 18) in dist via python')

if __name__ == "__main__":
    main()
