const fs = require('fs');
const path = require('path');

// Builder Version: 1.0.1 (Trigger for Custom Domain Deployment)

const ROOT = __dirname;
const SRC_RI = path.join(ROOT, 'ri');
const DIST = path.join(ROOT, 'dist');
const DIST_RI = path.join(DIST, 'ri');
const CONFIG_FILE = path.join(ROOT, 'config.json');

// Helper: Shuffle Array (Fisher-Yates)
function shuffle(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

// Main function
function build() {
    console.log('Starting build...');

    // Load Config
    let config = { domain: '' };

    // Priority 1: Environment Variable
    if (process.env.DOMAIN) {
        config.domain = process.env.DOMAIN;
        console.log('Loaded domain from environment variable.');
    }
    // Priority 2: Config File
    else if (fs.existsSync(CONFIG_FILE)) {
        try {
            const configContent = fs.readFileSync(CONFIG_FILE, 'utf8');
            const parsed = JSON.parse(configContent);
            if (parsed.domain) {
                config.domain = parsed.domain;
            }
            console.log('Loaded domain from config.json.');
        } catch (e) {
            console.warn('Failed to parse config.json, using default settings.');
        }
    }

    // Normalize domain (remove trailing slash)
    if (config.domain) {
        config.domain = config.domain.replace(/\/$/, '');
    }

    console.log(`Using domain prefix: "${config.domain}"`);

    // 1. Prepare Dist
    if (!fs.existsSync(DIST)) {
        fs.mkdirSync(DIST, { recursive: true });
    }
    // Instead of deleting the whole folder (which fails on Windows if server is running),
    // we just ensure the subfolders exist and overwrite files.
    if (!fs.existsSync(DIST_RI)) fs.mkdirSync(DIST_RI, { recursive: true });
    
    // Add .nojekyll to prevent Jekyll from processing the folder
    fs.writeFileSync(path.join(DIST, '.nojekyll'), '');

    // 2. Process Folders
    const types = ['h', 'v'];
    let counts = {};

    types.forEach(type => {
        const srcFolder = path.join(SRC_RI, type);
        const distFolder = path.join(DIST_RI, type);

        if (!fs.existsSync(srcFolder)) {
            console.warn(`Source folder not found: ${srcFolder}`);
            counts[type] = 0;
            return;
        }

        fs.mkdirSync(distFolder, { recursive: true });

        // Read and Filter Images
        let files = fs.readdirSync(srcFolder).filter(f => f.match(/\.(webp|jpg|jpeg|png|gif)$/i));

        // Shuffle
        files = shuffle(files);

        // Copy and Rename
        files.forEach((file, index) => {
            const srcPath = path.join(srcFolder, file);
            // User requested 1.webp, 2.webp, etc.
            const destPath = path.join(distFolder, `${index + 1}.webp`);
            fs.copyFileSync(srcPath, destPath);
        });

        counts[type] = files.length;
        console.log(`Processed ${type}: ${counts[type]} images.`);
    });

    // 3. Generate Single JS
    const jsContent = `
/**
 * Static Random Pic API
 * Generated by build script
 */
(function() {
    var counts = ${JSON.stringify(counts)};
    var domain = '${config.domain}';
    
    // Support relative paths for testing on preview domains and when served from the same origin
    if (typeof window !== 'undefined') {
        if (window.location.origin === domain) {
            domain = '';
        }
    }
    
    // State management for session consistency
    var sessionRandomH = null;
    var sessionRandomV = null;

    // Helper: Get random URL for a type (h or v), persistent per session
    function getRandomUrl(type) {
        if (!counts[type] || counts[type] === 0) return '';
        
        // Return existing session URL if available
        if (type === 'h' && sessionRandomH) return sessionRandomH;
        if (type === 'v' && sessionRandomV) return sessionRandomV;

        // Generate new if not exists
        var num = Math.floor(Math.random() * counts[type]) + 1;
        var url = domain + '/ri/' + type + '/' + num + '.webp';

        // Save to session state
        if (type === 'h') sessionRandomH = url;
        if (type === 'v') sessionRandomV = url;

        return url;
    }

    // Expose global functions
    window.getRandomPicH = function() { return getRandomUrl('h'); };
    window.getRandomPicV = function() { return getRandomUrl('v'); };

    // 1. Logic for Background (Customized based on user request)
    function setRandomBackground() { 
         // Get random URL using the helper (Dynamic count & domain)
         const bgUrl = getRandomUrl('h');
          
         // Find the background box element 
         const bgBox = document.getElementById('bg-box'); 
          
         if (bgBox) { 
             // Preload image 
             const img = new Image(); 
             img.onload = function() { 
                 bgBox.style.backgroundImage = \`url('\${bgUrl}')\`; 
                 bgBox.classList.add('loaded'); 
                 console.log('Random background loaded:', bgUrl); 
                  
                 // Set CSS variables for transparency effects 
                 document.documentElement.style.setProperty('--card-bg', 'var(--card-bg-transparent)'); 
                 document.documentElement.style.setProperty('--float-panel-bg', 'var(--float-panel-bg-transparent)'); 
             }; 
             img.onerror = function() { 
                 console.error('Failed to load background image:', bgUrl); 
             }; 
             img.src = bgUrl; 
         } else { 
             // Fallback: If no #bg-box, check for data-random-bg for backward compatibility/other elements
             // This keeps the generic functionality available if needed, but prioritizes the user's specific logic above.
             initGenericBackgrounds();
         } 
    }

    // 2. Logic for Image Tags (Generic)
    function initImgTags() {
        var imgTags = document.getElementsByTagName('img');
        for (var i = 0; i < imgTags.length; i++) {
            var img = imgTags[i];
            var alt = img.getAttribute('alt');
            var src = img.getAttribute('src');

            if (alt === 'random:h' || (src && src.indexOf('/random/h') !== -1)) {
                img.src = getRandomUrl('h');
            } else if (alt === 'random:v' || (src && src.indexOf('/random/v') !== -1)) {
                img.src = getRandomUrl('v');
            }
        }
    }

    // Helper for generic data-random-bg (as a backup or secondary feature)
    function initGenericBackgrounds() {
        var bgElements = document.querySelectorAll('[data-random-bg]');
        bgElements.forEach(function(el) {
            // Skip if it is the bg-box we already handled (though setRandomBackground handles #bg-box specifically)
            if (el.id === 'bg-box') return;

            var type = el.getAttribute('data-random-bg');
            if (type === 'h' || type === 'v') {
                var url = getRandomUrl(type);
                if (url) {
                    var img = new Image();
                    img.onload = function() {
                        el.style.backgroundImage = 'url("' + url + '")';
                        el.classList.add('loaded');
                    };
                    img.src = url;
                }
            }
        });
    }

    function init() {
        setRandomBackground();
        initImgTags();
    }
  
    // Run on initial load 
    if (document.readyState === 'loading') { 
        document.addEventListener('DOMContentLoaded', init); 
    } else { 
        init(); 
    } 
  
    // Swup integration
    function setupSwup() {
        if (window.swup && window.swup.hooks) {
            // Register hook for content replacement
            window.swup.hooks.on('content:replace', init);
            console.log('Random Pic API: Registered with Swup hooks.');
        }
    }

    if (window.swup) {
        setupSwup();
    } else {
        document.addEventListener('swup:enable', setupSwup);
    }

    // Legacy Swup support
    document.addEventListener('swup:contentReplaced', init); 
})();
`;
    fs.writeFileSync(path.join(DIST, 'random.js'), jsContent.trim());

    // Copy index.html if exists and not empty
    const indexSrc = path.join(ROOT, 'index.html');
    if (fs.existsSync(indexSrc)) {
        const stats = fs.statSync(indexSrc);
        if (stats.size > 0) {
            fs.copyFileSync(indexSrc, path.join(DIST, 'index.html'));
            console.log('Copied index.html to dist');
        } else {
            console.log('index.html is empty, creating a demo page in dist...');
            createDemoHtml(counts);
        }
    } else {
        createDemoHtml(counts);
    }

    // 3. Generate Hero Home Page (Always use the React one for Premium experience)
    createDemoHtml(counts);
    // 4. Generate api.json for external consumption
    const apiData = {
        lastBuild: new Date().toISOString(),
        domain: config.domain,
        counts: counts,
        images: {
            h: Array.from({ length: counts.h }, (_, i) => `${config.domain}/ri/h/${i + 1}.webp`),
            v: Array.from({ length: counts.v }, (_, i) => `${config.domain}/ri/v/${i + 1}.webp`)
        }
    };
    fs.writeFileSync(path.join(DIST, 'api.json'), JSON.stringify(apiData, null, 2));
    console.log('Generated api.json');

    // 5. Generate Gallery Page
    createGalleryHtml(counts, config);

    console.log('Build complete. Output is in /dist folder.');
}

function createGalleryHtml(counts, config) {
    const types = Object.keys(counts);

    // Read assets to inline
    const readAsset = (name) => {
        const p = path.join(ROOT, 'assets', name);
        if (fs.existsSync(p)) { console.log('Inlining ' + name); return fs.readFileSync(p, 'utf8'); }
        console.warn('WARNING: assets/' + name + ' not found!'); return '';
    };
    const appCode = readAsset('gallery-app.jsx');

    // Build image data JSON
    const imageData = {};
    types.forEach(type => {
        const count = counts[type];
        if (count === 0) return;
        const max = 100, step = count > max ? Math.floor(count / max) : 1, imgs = [];
        for (let i = 1; i <= count && imgs.length < max; i += step)
            imgs.push({ id: type + '-' + i, src: '/ri/' + type + '/' + i + '.webp', type });
        imageData[type] = { images: imgs, total: count };
    });

    const html = `<!DOCTYPE html>
<html lang="zh-TW">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Gallery - Static Random Pic API</title>
<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🖼️</text></svg>">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800&family=Outfit:wght@400;700;900&display=swap" rel="stylesheet">
<style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{--a:#a78bfa;--ap:#f472b6;--ag:rgba(167,139,250,.35);--gl:rgba(255,255,255,.06);--gb:rgba(255,255,255,.1);--bg:#07070f;--text:#e2e8f0;--card-bg:rgba(255,255,255,.03);--card-border:rgba(255,255,255,.06);--card-hover:rgba(255,255,255,.18);--btn-bg:rgba(255,255,255,.06);--nav-btn-bg:rgba(255,255,255,.06);--btn-hover:rgba(255,255,255,.1);--btn-on-bg:rgba(255,255,255,.9);--btn-on-text:#0f0f1a;--f:'Inter',system-ui,sans-serif;--fd:'Outfit',sans-serif;--e:cubic-bezier(.4,0,.2,1)}
:root[data-theme='light']{--a:#8b5cf6;--ap:#ec4899;--ag:rgba(139,92,246,.25);--gl:rgba(0,0,0,.04);--gb:rgba(0,0,0,.1);--bg:#f8fafc;--text:#0f172a;--card-bg:rgba(255,255,255,.6);--card-border:rgba(0,0,0,.08);--card-hover:rgba(0,0,0,.15);--btn-bg:rgba(0,0,0,.05);--nav-btn-bg:rgba(0,0,0,.05);--btn-hover:rgba(0,0,0,.1);--btn-on-bg:#0f172a;--btn-on-text:#fff}
html{scroll-behavior:smooth;overflow-y:scroll;min-height:100.1vh}
body{font-family:var(--f);background:var(--bg);color:var(--text);min-height:100vh;overflow-x:hidden;transition:background .4s var(--e),color .4s var(--e)}
/* Animated mesh gradient background - pure CSS, zero JS */
.mesh-bg{position:fixed;top:0;left:0;width:100vw;height:100vh;z-index:0;pointer-events:none;opacity:.4;transition:opacity .4s;overflow:hidden;transform:translateZ(0);backface-visibility:hidden}
.mesh-bg::before,.mesh-bg::after{content:'';position:absolute;border-radius:50%;filter:blur(120px);will-change:transform;backface-visibility:hidden;transform:translateZ(0);animation:meshDrift 20s ease-in-out infinite alternate}
.mesh-bg::before{width:60vw;height:60vh;top:-10%;left:-10%;background:radial-gradient(circle,rgba(167,139,250,.5) 0%,transparent 70%);animation-delay:0s}
.mesh-bg::after{width:50vw;height:50vh;bottom:-10%;right:-10%;background:radial-gradient(circle,rgba(244,114,182,.4) 0%,transparent 70%);animation-delay:-10s}
.mesh-orb{position:absolute;border-radius:50%;filter:blur(100px);will-change:transform;backface-visibility:hidden;transform:translateZ(0);animation:meshDrift 25s ease-in-out infinite alternate-reverse}
.mesh-orb:nth-child(1){width:40vw;height:40vh;top:30%;left:40%;background:radial-gradient(circle,rgba(56,189,248,.3) 0%,transparent 70%);animation-delay:-5s}
@keyframes meshDrift{0%{transform:translate3d(0,0,0) scale(1)}25%{transform:translate3d(5vw,-8vh,0) scale(1.1)}50%{transform:translate3d(-3vw,6vh,0) scale(.95)}75%{transform:translate3d(8vw,3vh,0) scale(1.05)}100%{transform:translate3d(-5vw,-5vh,0) scale(1)}}
:root[data-theme='light'] .mesh-bg{opacity:.25}
:root[data-theme='light'] .mesh-bg::before{background:radial-gradient(circle,rgba(139,92,246,.35) 0%,transparent 70%)}
:root[data-theme='light'] .mesh-bg::after{background:radial-gradient(circle,rgba(236,72,153,.25) 0%,transparent 70%)}
:root[data-theme='light'] .mesh-orb:nth-child(1){background:radial-gradient(circle,rgba(56,189,248,.2) 0%,transparent 70%)}
.app{position:relative;z-index:1;max-width:1400px;margin:0 auto;padding:40px 24px 120px;min-height:100vh;overflow-anchor:none}
.nav-group-right{position:fixed;top:32px;right:32px;z-index:9999;display:flex;gap:12px}
.nav-group-left{position:fixed;top:32px;left:32px;z-index:9999;display:flex;gap:12px}
.nav-btn{width:48px;height:48px;border-radius:14px;background:var(--nav-btn-bg);border:1px solid var(--gb);color:var(--text);cursor:pointer;display:flex;align-items:center;justify-content:center;transition:all 0.3s var(--e);text-decoration:none;box-shadow:0 4px 16px rgba(0,0,0,0.1)}
.nav-btn:hover{transform:translateY(-2px) scale(1.05);box-shadow:0 8px 32px var(--ag);border-color:var(--a)}
.nav-btn-lang{width:54px}
.hdr{text-align:center;padding:14px 0 22px}
.hdr h1{font-family:var(--fd);font-weight:900;font-size:clamp(2rem,5vw,3.4rem);background:linear-gradient(135deg,#fff 0%,var(--a) 50%,var(--ap) 100%);-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent;letter-spacing:-1px;line-height:1.1}
.sub{font-size:.85rem;color:var(--text);opacity:.5;font-weight:300;margin-top:4px;letter-spacing:1.5px;text-transform:uppercase}
.fbar{display:flex;justify-content:center;gap:10px;flex-wrap:wrap;margin-bottom:28px}
.fc{font-family:var(--f);padding:8px 20px;border-radius:999px;border:1px solid var(--gb);background:var(--btn-bg);color:var(--text);opacity:.7;font-size:.82rem;font-weight:500;cursor:pointer;transition:all .25s var(--e);user-select:none;outline:none}
.fc:hover{background:var(--btn-hover);opacity:1;border-color:var(--gb);transform:translateY(-2px);box-shadow:0 6px 20px rgba(0,0,0,.15)}
.fc.on{background:var(--btn-on-bg);color:var(--btn-on-text);opacity:1;border-color:transparent;font-weight:600;box-shadow:0 0 25px var(--ag);transform:translateY(-1px)}
.masonry-js{display:flex;gap:16px;align-items:flex-start}
.masonry-col{display:flex;flex-direction:column;gap:16px;flex:1;min-width:0}
@media(max-width:860px){.masonry-js{gap:10px}.masonry-col{gap:10px}}
.gallery-card{position:relative;border-radius:14px;overflow:hidden;animation:cReveal .5s cubic-bezier(.16,1,.3,1) both;animation-delay:var(--d,0ms);transition:transform .2s var(--e),box-shadow .3s var(--e);background:var(--card-bg);border:1px solid var(--card-border);min-height:120px;cursor:pointer}
@keyframes cReveal{from{opacity:0;transform:translateY(20px) scale(.98)}to{opacity:1;transform:translateY(0) scale(1)}}
.gallery-card:hover{transform:translateY(-4px);box-shadow:0 20px 50px rgba(0,0,0,.25),0 0 20px var(--ag);border-color:var(--card-hover);z-index:2}
.gallery-card img{display:block;width:100%;height:auto;opacity:0;transition:opacity .5s var(--e);min-height:120px;object-fit:cover;background:rgba(0,0,0,.05)}
.gallery-card img.ok{opacity:1}
.shim{width:100%;padding-bottom:66%;background:linear-gradient(110deg,rgba(255,255,255,.02) 30%,rgba(255,255,255,.06) 50%,rgba(255,255,255,.02) 70%);background-size:200% 100%;animation:shm 1.5s ease-in-out infinite}
@keyframes shm{0%{background-position:200% 0}100%{background-position:-200% 0}}
.lb{position:fixed;inset:0;z-index:10000;background:rgba(5,5,16,.92);backdrop-filter:blur(30px);-webkit-backdrop-filter:blur(30px);display:flex;align-items:center;justify-content:center;animation:lbIn .3s var(--e)}
.lb.lb-out{animation:lbOut .22s var(--e) forwards}
@keyframes lbIn{from{opacity:0}to{opacity:1}}
@keyframes lbOut{from{opacity:1}to{opacity:0}}
.lb-wrap{position:relative;display:flex;align-items:center;justify-content:center}
.lb-wrap img{max-width:88vw;max-height:88vh;border-radius:10px;box-shadow:0 30px 80px rgba(0,0,0,.6);transition:opacity .3s;opacity:0;user-select:none}
.lb-wrap img.lb-ok{opacity:1}
.lb-nav{position:fixed;top:50%;transform:translateY(-50%);background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.12);color:rgba(255,255,255,.7);width:48px;height:48px;border-radius:50%;display:flex;align-items:center;justify-content:center;cursor:pointer;transition:all .25s var(--e);outline:none}
.lb-prev{left:24px}.lb-next{right:24px}
.lb-nav:hover{background:rgba(255,255,255,.15);border-color:rgba(255,255,255,.3);transform:translateY(-50%) scale(1.12);color:#fff;box-shadow:0 0 20px var(--ag)}
.lb-count{position:fixed;bottom:28px;left:50%;transform:translateX(-50%);font-size:.78rem;color:rgba(255,255,255,.35);font-weight:500;letter-spacing:2px;user-select:none}
.lb-close{position:fixed;top:24px;right:24px;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.12);color:rgba(255,255,255,.5);width:44px;height:44px;border-radius:50%;display:flex;align-items:center;justify-content:center;cursor:pointer;transition:all .25s var(--e);outline:none}
.lb-close:hover{background:rgba(255,255,255,.12);color:#fff;transform:rotate(90deg)}
.lb-spin{position:absolute;width:36px;height:36px;border:3px solid rgba(255,255,255,.1);border-top-color:var(--a);border-radius:50%;animation:sp .8s linear infinite}
@keyframes sp{to{transform:rotate(360deg)}}
::-webkit-scrollbar{width:5px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:rgba(255,255,255,.1);border-radius:3px}::-webkit-scrollbar-thumb:hover{background:rgba(255,255,255,.2)}
</style>
</head>
<body>
<div class="mesh-bg"><div class="mesh-orb"></div></div>
<div id="root"><div style="position:absolute;top:30vh;left:50%;transform:translate(-50%,-50%);display:flex;flex-direction:column;align-items:center;gap:16px"><div style="width:40px;height:40px;border:3px solid rgba(255,255,255,.08);border-top-color:var(--a);border-radius:50%;animation:sp 1s linear infinite"></div><p style="color:rgba(255,255,255,.3);font-size:.85rem;letter-spacing:1px">Loading Gallery...</p></div></div>

<script>window.__GALLERY_DATA__=${JSON.stringify(imageData)};</script>
<script src="https://unpkg.com/react@18/umd/react.production.min.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js" crossorigin></script>
<script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
<script type="text/babel">
${appCode}
</script>
</body>
</html>`;

    fs.writeFileSync(path.join(DIST, 'gallery.html'), html);
}

function createDemoHtml(counts) {
    const homeCode = fs.readFileSync(path.join(ROOT, 'assets', 'home-app.jsx'), 'utf8');
    const etherCode = fs.readFileSync(path.join(ROOT, 'assets', 'liquid-ether-engine.js'), 'utf8');

    const html = `<!DOCTYPE html>
<html lang="zh-TW">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Static Random Pic API - Premium Delivery</title>
<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🖼️</text></svg>">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800&family=Outfit:wght@400;700;900&display=swap" rel="stylesheet">
<style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{--a:#a78bfa;--ap:#f472b6;--ag:rgba(167,139,250,.35);--gl:rgba(255,255,255,.06);--gb:rgba(255,255,255,.1);--bg:#07070f;--text:#e2e8f0;--card-bg:rgba(255,255,255,.02);--card-border:rgba(255,255,255,.06);--card-hover:rgba(255,255,255,.15);--btn-bg:rgba(255,255,255,.9);--btn-text:#0f0f1a;--btn-sec-bg:var(--gl);--btn-sec-text:#fff;--nav-btn-bg:rgba(255,255,255,.06);--f:'Inter',system-ui,sans-serif;--fd:'Outfit',sans-serif;--e:cubic-bezier(.4,0,.2,1)}
:root[data-theme='light']{--a:#8b5cf6;--ap:#ec4899;--ag:rgba(139,92,246,.25);--gl:rgba(0,0,0,.04);--gb:rgba(0,0,0,.1);--bg:#f8fafc;--text:#0f172a;--card-bg:rgba(255,255,255,.6);--card-border:rgba(0,0,0,.08);--card-hover:rgba(0,0,0,.15);--btn-bg:#0f172a;--btn-text:#fff;--btn-sec-bg:var(--gl);--btn-sec-text:#0f172a;--nav-btn-bg:rgba(0,0,0,.05)}
html{scroll-behavior:smooth;overflow-y:scroll;min-height:100.1vh}
body{font-family:var(--f);background:var(--bg);color:var(--text);min-height:100vh;overflow-x:hidden;transition:background .4s var(--e),color .4s var(--e)}
body.hide-cursor,body.hide-cursor *{cursor:none!important}
#ether-bg{position:fixed;top:0;left:0;width:100vw;height:100vh;z-index:0;pointer-events:none}
.cur-dot{position:fixed;top:-6px;left:-6px;width:12px;height:12px;border-radius:50%;background:var(--a);pointer-events:none;z-index:99999;mix-blend-mode:difference;transition:width .2s,height .2s,top .2s,left .2s,background .2s}
.cur-dot.h{width:44px;height:44px;top:-22px;left:-22px;background:rgba(167,139,250,.12);border:1.5px solid var(--a)}
.cur-ring{position:fixed;top:-22px;left:-22px;width:44px;height:44px;border-radius:50%;border:1px solid rgba(167,139,250,.25);pointer-events:none;z-index:99998;transition:width .3s,height .3s,top .3s,left .3s,border-color .3s,opacity .3s}
.cur-ring.h{width:64px;height:64px;top:-32px;left:-32px;border-color:rgba(244,114,182,.35);opacity:.4}
@media(hover:none){.cur-dot,.cur-ring{display:none!important}body.hide-cursor,body.hide-cursor *{cursor:auto!important}}
.app{position:relative;z-index:1;max-width:1400px;margin:0 auto;padding:40px 24px 120px;min-height:100vh;overflow-anchor:none}
.flex-col{display:flex;flex-direction:column;align-items:center}
.hero{text-align:center;padding:8vh 0 10vh}
.nav-group-right{position:fixed;top:32px;right:32px;z-index:10001;display:flex;gap:12px}
.nav-btn{width:48px;height:48px;border-radius:50%;background:var(--nav-btn-bg);border:1px solid var(--gb);color:var(--text);cursor:pointer;display:flex;align-items:center;justify-content:center;transition:all 0.3s var(--e);backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);text-decoration:none;box-shadow:0 8px 32px rgba(0,0,0,0.15)}
.nav-btn:hover{transform:translateY(-2px) scale(1.1);box-shadow:0 12px 48px var(--ag);border-color:var(--a)}
.nav-btn-lang{width:54px}
.hero-title{font-family:var(--fd);font-size:clamp(2.5rem,8vw,5rem);font-weight:800;letter-spacing:-1px;margin-bottom:24px;background:linear-gradient(135deg,var(--text) 0%,var(--a) 50%,var(--ap) 100%);-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent;line-height:1.2;padding:20px 0}
.hero-title span{display:inline-block;background:inherit;-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent;animation:float 4s ease-in-out infinite;vertical-align:middle}
@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-8px)}}
.hero-sub{font-size:clamp(1rem,3vw,1.3rem);color:var(--text);opacity:.6;font-weight:300;letter-spacing:1px;margin-bottom:48px;max-width:600px;margin-left:auto;margin-right:auto}
.hero-btns{display:flex;gap:16px;justify-content:center;flex-wrap:wrap;max-width:900px;margin:0 auto}
.btn-primary,.btn-secondary{font-family:var(--f);padding:14px 28px;border-radius:999px;font-size:0.95rem;font-weight:600;cursor:pointer;backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);transition:all .3s var(--e);text-decoration:none;display:flex;align-items:center;gap:10px;white-space:nowrap}
.btn-primary{background:var(--btn-bg);color:var(--btn-text);border:1px solid transparent;box-shadow:0 0 25px var(--ag)}
.btn-primary:hover{transform:translateY(-3px);box-shadow:0 10px 40px var(--ag);border-color:var(--gb)}
.btn-secondary{background:var(--btn-sec-bg);color:var(--btn-sec-text);border:1px solid var(--gb)}
.nav-group-right{position:fixed;top:32px;right:32px;z-index:10001;display:flex;gap:12px}
.nav-group-left{position:fixed;top:32px;left:32px;z-index:10001;display:flex;gap:12px}
.nav-btn-right{position:fixed;top:32px;right:32px;z-index:10001}
.nav-btn-left{position:fixed;top:32px;left:32px;z-index:10001}
.nav-btn-lang{width:54px}
.live-demo{margin-top:20px;width:100%;max-width:1400px;margin-left:auto;margin-right:auto}
.section-title{font-family:var(--fd);font-size:2.8rem;font-weight:900;text-align:center;margin-bottom:48px;letter-spacing:-0.02em}
.demo-stack{display:flex;flex-direction:column;gap:64px;width:100%}
.v-card-wrap{width:100%;display:flex;justify-content:center}
.v-card-wrap .demo-card{width:100%;max-width:720px}
.demo-card{background:var(--card-bg);border:1px solid var(--card-border);border-radius:32px;padding:48px;transition:transform .15s ease-out,box-shadow .4s var(--e),background .4s var(--e),border-color .4s var(--e);transform-style:preserve-3d;will-change:transform;backdrop-filter:blur(24px);-webkit-backdrop-filter:blur(24px);contain:layout}
.demo-card:hover{box-shadow:0 30px 80px rgba(0,0,0,.2),0 0 40px var(--ag);border-color:var(--card-hover);background:var(--card-hover);z-index:2}
.demo-header{margin-bottom:20px}
.demo-header h3{font-family:var(--fd);font-size:1.8rem;color:var(--text);font-weight:700;margin-bottom:8px}
.code-hint{font-family:monospace;font-size:.85rem;color:var(--text);opacity:.7;background:var(--gl);padding:6px 14px;border-radius:6px;display:inline-block;border:1px solid var(--gb)}
.demo-img-box{position:relative;width:100%;border-radius:12px;overflow:hidden;background:rgba(0,0,0,.05);cursor:pointer;contain:size layout;display:block}
.demo-img-box img{width:100%;height:100%;object-fit:cover;opacity:0;transition:opacity .6s var(--e);display:block;backface-visibility:hidden}
.demo-img-box img.ok{opacity:1}
.demo-img-box .shim{position:absolute;inset:0;z-index:1;background:linear-gradient(110deg,rgba(255,255,255,.02) 30%,rgba(255,255,255,.06) 50%,rgba(255,255,255,.02) 70%);background-size:200% 100%;animation:shm 1.5s ease-in-out infinite;pointer-events:none}
.refresh-hint{position:absolute;bottom:20px;left:50%;transform:translateX(-50%) translateY(20px);background:rgba(0,0,0,.7);backdrop-filter:blur(12px);color:#fff;font-size:.75rem;padding:8px 20px;border-radius:99px;opacity:0;transition:all .3s var(--e);border:1px solid rgba(255,255,255,.1);pointer-events:none;z-index:2}
.demo-card:hover .refresh-hint{opacity:1;transform:translateX(-50%) translateY(0)}
.shine{position:absolute;inset:0;background:radial-gradient(circle at var(--sx,50%) var(--sy,50%),rgba(255,255,255,.12),transparent 50%);opacity:0;transition:opacity .3s;pointer-events:none;z-index:3}
.demo-card:hover .shine{opacity:1}
.shim{position:absolute;inset:0;background:linear-gradient(110deg,rgba(255,255,255,.02) 30%,rgba(255,255,255,.06) 50%,rgba(255,255,255,.02) 70%);background-size:200% 100%;animation:shm 1.5s ease-in-out infinite}
@keyframes shm{0%{background-position:200% 0}100%{background-position:-200% 0}}
</style>
</head>
<body>
<div id="ether-bg"></div>
<div id="root"></div>

<script src="https://unpkg.com/three@0.149.0/build/three.min.js"><\/script>
<script>
${etherCode}
<\/script>
<script>
document.addEventListener('DOMContentLoaded',function(){var b=document.getElementById('ether-bg');if(b&&typeof LiquidEtherEngine!=='undefined'){try{new LiquidEtherEngine(b,{colors:['#FF2A54','#a78bfa','#38BDF8'],autoIntensity:1.5,resolution:0.3,iterations_poisson:16,BFECC:false})}catch(e){console.warn('LiquidEther:',e)}}});
<\/script>
<script>window.__COUNTS__=${JSON.stringify(counts)};<\/script>
<script src="https://unpkg.com/react@18/umd/react.production.min.js" crossorigin><\/script>
<script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js" crossorigin><\/script>
<script src="https://unpkg.com/@babel/standalone/babel.min.js"><\/script>
<script type="text/babel">
${homeCode}
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<HomeApp />);
<\/script>
</body>
</html>`;
    fs.writeFileSync(path.join(DIST, 'index.html'), html);
    console.log('Created premium index.html (React 18) in dist');
}

build();
